export default {
  questions: [
    {
      id: 2,
      label: 'Question 0: Lorem ipsum dolor sit amet?',
      max_selections: 1,
      order: 0,
      options: [
        {
          id: 5,
          key: '546723985234',
          label: 'Tempor incididunt',
          order: 0,
          question: 2,
          quiz: 2,
        },
        {
          id: 18,
          key: '754839057234',
          label: 'Quis nostrud',
          order: 1,
          question: 2,
          quiz: 2,
        },
        {
          id: 6,
          key: '5469783205',
          label: "Exercitation",
          order: 2,
          question: 2,
          quiz: 2,
        },
      ],
    },
    {
      id: 3,
      label: 'Question 1: Lorem ipsum dolor sit amet?',
      max_selections: 1,
      order: 0,
      options: [
        {
          id: 5,
          key: '676457465734352',
          label: 'Tempor incididunt',
          order: 0,
          question: 2,
          quiz: 2,
        },
        {
          id: 18,
          key: '65746435623454',
          label: 'Quis nostrud',
          order: 1,
          question: 2,
          quiz: 2,
        },
        {
          id: 6,
          key: '6547653456342564',
          label: "Exercitation",
          order: 2,
          question: 2,
          quiz: 2,
        },
      ],
    },
    {
      id: 4,
      label: 'Question 2: Lorem ipsum dolor sit amet?',
      max_selections: 1,
      order: 0,
      options: [
        {
          id: 5,
          key: '6547354256432543',
          label: 'Tempor incididunt',
          order: 0,
          question: 2,
          quiz: 2,
        },
        {
          id: 18,
          key: '76543754236543',
          label: 'Quis nostrud',
          order: 1,
          question: 2,
          quiz: 2,
        },
        {
          id: 6,
          key: '4657435645674534',
          label: "Exercitation",
          order: 2,
          question: 2,
          quiz: 2,
        },
      ],
    },
    {
      id: 5,
      label: 'Question 3: Lorem ipsum dolor sit amet?',
      max_selections: 1,
      order: 0,
      options: [
        {
          id: 5,
          key: '564365324',
          label: 'Tempor incididunt',
          order: 0,
          question: 2,
          quiz: 2,
        },
        {
          id: 18,
          key: '563546543',
          label: 'Quis nostrud',
          order: 1,
          question: 2,
          quiz: 2,
        },
        {
          id: 6,
          key: '34657456546345',
          label: "Exercitation",
          order: 2,
          question: 2,
          quiz: 2,
        },
      ],
    },
  ]
}